import logging
from typing import Optional

from schemas import AgentActRequest, AgentAction
from validator import validate_action, ValidationError
from llm.router import ModelRouter

log = logging.getLogger("praxsight.agent_engine")

class AgentPipeline:
    """
    Coordinates the PraxLight Controlled Execution Pipeline.
    UNDERSTAND -> PLAN -> CHECK PERMISSIONS -> RETRIEVE -> REASON -> VALIDATE -> ACTION -> VERIFY
    """
    def __init__(self, model_router: ModelRouter):
        self.router = model_router
        
    async def execute(self, req: AgentActRequest) -> AgentAction:
        """Execute the full agent pipeline for a given request."""
        # 1. CHECK PERMISSIONS & RETRIEVE (Local RAG)
        # If the task implies knowledge retrieval and it's permitted, we inject RAG context.
        # This occurs before reasoning, satisfying the pipeline diagram in the master prompt.
        if req.tool_permissions.allow_rag:
            try:
                from rag.retriever import retrieve_context, format_retrieved_context
                # We retrieve using the user's task as the query
                contexts = retrieve_context(req.task)
                if contexts:
                    rag_text = format_retrieved_context(contexts)
                    # We inject this safely into the text_context of the request so the LLM sees it
                    from schemas import SanitizedTextNode
                    req.text_context.append(SanitizedTextNode(
                        psId="RAG_CONTEXT",
                        text=rag_text,
                        bbox={}
                    ))
                    log.info("Injected %d RAG contexts into agent reasoning", len(contexts))
            except ImportError:
                log.warning("RAG module not available, skipping retrieval.")
            except Exception as e:
                log.error("RAG retrieval failed during agent pipeline: %s", e)

        # 2. REASON
        # The router uses the LLM to deduce the best action based on the safe context
        action = await self.router.reason(req)
        
        # If no action is returned, fallback to a safe 'wait' action
        if not action:
            action = AgentAction(
                action="wait",
                reason="No valid action generated by the reasoning engine.",
                risk="low"
            )

        # 3. VALIDATE
        try:
            action = validate_action(action, req.elements)
        except ValidationError as e:
            log.warning("Agent produced invalid action: %s", e)
            # Override with a safe fail state
            action = AgentAction(
                action="wait",
                reason=f"Validation failed: {e}",
                risk="low",
                validated=False,
                status="DRAFT"
            )
            
        return action
